---
- name: Install basic packages
  yum: name={{ item }} state=present
  with_items:
      - bash-completion
      - fedora-easy-karma
      - htop
      - screen
      - tmux
      - tree
      - vim-enhanced

- name: Install packages requires to gather Pulp facts
  yum: name={{ item }} state=present
  with_items:
      - rpm-build
      - selinux-policy

- name: Gathering Pulp facts
  pulp_facts:
