---
- name: Install lazy packages
  package:
    state: present
    name:
      - squid
      - httpd
      - mod_ssl

- name: Install squid proxy configuration
  copy: src=squid.conf dest=/etc/squid/squid.conf
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6

- name: Install squid-3.1 proxy configuration
  copy: src=squid-3.1.conf dest=/etc/squid/squid.conf
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- file: path=/var/spool/squid state=directory owner=squid group=squid mode=750

- name: Start and enable Squid service
  service: name=squid state=started enabled=yes
